Enabling .NET 9 tests for SF SDK packages
Azure/service-fabric-aspnetcore pull request #124
Opened 2024-10-02 13:36 UTC by plave0

This PR enables tests for .NET 9 builds. 

Additionally, we are moving away from the `buils.ps1` script, which uses `msbuild` under the hood. Instead, we are moving to the `dotnet` tool, in the aim of streamlining the build process and infrastructure. 

Internal ADO work item: https://dev.azure.com/msazure/One/_workitems/edit/29603235

2024-10-04 07:43 UTC, plave0 commented on .github/workflows/build.yml
> +        run: dotnet build code.sln
I have tested building the whole solution using `dotnet`, and it works. The same change will be implemented in `service-fabric-services-and-actors-dotnet`.

2024-10-04 22:12 UTC, olegsych requested changes

2024-10-04 22:12 UTC, olegsych commented on .github/workflows/build.yml
> +        run: dotnet build code.sln
Let's do `dotnet build buildAll.proj` and get rid of the build.ps1 as I've explained in the services and actors PR.

2024-10-09 23:22 UTC, olegsych approved these changes

2024-10-10 12:12 UTC, merged